language: node_js
node_js:
 - "node"

cache: npm

script: npm run build && echo 'JohnathanIrvin.com' > CNAME

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 target_branch: master
 keep_history: true
 on:
   branch: develop
