language: node_js
node_js:
 - "node"

cache: npm

jobs:
  include:
    script: echo 'JohnathanIrvin.com' > CNAME
    script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 target_branch: master
 keep_history: true
 on:
   branch: develop
