name: Automatic Release

on:
  push:
    branches:
      - trunk

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release PR or Publish Release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          target-branch: trunk
          skip-github-pull-request: true